# Generated by Django 3.2.8 on 2022-04-09 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audisl', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AudioDb',
        ),
    ]
